### ISSUE TITLE
Mapbox PHP warning

### ISSUE THREAD

**Issue by asuh** [dshanske/simple-location#104]
After entering a longitude and latitude into the Location fields, the following warning appears:
`Warning: array_key_exists(): The first argument should be either a string or an integer in /[...]/plugins/simple-location/includes/class-map-provider-mapbox.php on line 87`

**Comment by dshanske** [comment]
@asuh About to push version 3.7.0 which has a check for this issue. Tell me if it resolves.

**Comment by dshanske** [comment]
@asuh Can you check this?

**Comment by asuh** [comment]
I can't reproduce this error now so I'm closing out!
