### ISSUE TITLE
Add location lookup by address

### ISSUE THREAD

**Issue by dshanske** [dshanske/simple-location#12]
If no geo coordinates are available

**Comment by thejeshgn** [comment]
Specially useful for sites without https.

I usually use https://www.latlong.net/ and then copy coordinates.

**Comment by dshanske** [comment]
I have plans for additional ways to lookup location automatically.

**Comment by dshanske** [comment]
@thejeshgn Look will be int he next version. I'm working on it now. It will be provided for all of the providers that support it.

**Comment by dshanske** [comment]
This is now a supported location provider in the development branch, and an option for search in the debugger.
