### ISSUE TITLE
Airport Weather Error

### ISSUE THREAD

**Issue by webkernel** [dshanske/simple-location#166]
Hi David,

Tried to add Airport Weather Widget and got these errors (Simple Location Plugin is installed).

Warning: Illegal string offset 'latitude' in /home/paulopin/public_html/wp-content/plugins/simple-location/includes/class-sloc-airport-widget.php on line 62

Warning: Illegal string offset 'longitude' in /home/paulopin/public_html/wp-content/plugins/simple-location/includes/class-sloc-airport-widget.php on line 62

**Comment by dshanske** [comment]
What airport were you putting in?

**Comment by webkernel** [comment]
LPPR
Oporto, Portugal

**Comment by dshanske** [comment]
I see the errors. It looks like I'm not validating the data I'm pulling with the airport locations. I'll fix it.

**Comment by webkernel** [comment]
Oh, many thanks for that.
