### ISSUE TITLE
Only secure locations allowed (Chrome)

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/simple-location#17]
Using Simple Location Version 3.0.2 (most recent stable from WordPress.org) in Chrome (both desktop and in Chrome mobile browser on Android):

When I click on "Get Location" button, I get a modal window that says:
> Only secure locations allowed (see https://goo.gl/Y0ZkNV)

This is on a "live" site and not a dev environment. I'm guessing it may be because I'm using http and not https while requesting my location?? I'm anything but a js expert, so this is just a guess...

In Firefox, it correctly asks "Would you like to share your location with this site?" and proceeds properly.

**Comment by dshanske** [comment]
https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only

**Comment by chrisaldrich** [comment]
<a href="https://github.com/dshanske/simple-location/issues/17#issuecomment-270302076" class="u-in-reply-to"></a>I had it on my roadmap to upgrade leisurely sometime this year. Now I have a reason to do it sooner than later. Damn....
