### ISSUE TITLE
Support for cycling in icon set

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/simple-location#179]
I only noticed because I actually went to post something while cycling around the neighborhood, but you seem to be missing a cycling option and a bicycle icon.

The only other edge cases I can immediately think of are scooter, roller skates, tractor, skateboard, gondola, and horse drawn carriage. Though these may be harder to find icons for and exceptionally rare in any case…

Good job on having nearly every other mode of transportation by the way.

(Originally published at: https://boffosocko.com/?p=55773343)

**Comment by dshanske** [comment]
Point of fact... https://github.com/dshanske/simple-location/blob/trunk/svgs/fa-biking.svg

**Comment by dshanske** [comment]
I forgot to add it to the menu
