### ISSUE TITLE
Uncaught Error: Call to a member function set() on null

### ISSUE THREAD

**Issue by bekopharm** [dshanske/simple-location#192]
Module crashes with a fatal php error. I played with this some time ago but never made it public (only private posts) because the configured mapbox provider set a cookie. I don't remember if I removed the API key any more but I think so because it's gone from settings.

After the update today I noticed that there is one public location checkin but when I try to edit the post php crashes.

Simple Location: `4.1.10 `
PHP: `7.4`

```txt
PHP Fatal error:  Uncaught Error: Call to a member function set() on null in wp-content/plugins/simple-location/includes/class-loc-view.php:204
Stack trace:
#0 wp-content/plugins/simple-location/includes/class-loc-view.php(363): Loc_View::get_map()
#1 wp-includes/class-wp-hook.php(287): Loc_View::content_map()
#2 wp-includes/plugin.php(206): WP_Hook->apply_filters()
#3 wp-includes/post-template.php(253): apply_filters()
#4 wp-content/themes/sempress/image.php(86): the_content()
#5 wp-includes/template-loader.php(106): include('...')
#6 wp-blog-header.php(19): require_once('...')
#7 index.php(17): require('...')
#8 {main}
```

Public blog pages says:  `Error: Invalid Map Provider`

**Comment by dshanske** [comment]
Already fixed in trunk
