### ISSUE TITLE
Trying to save the user

### ISSUE THREAD

**Issue by thejeshgn** [dshanske/simple-location#193]
WordPress version 5.5.1
Current theme: SemPress (version 1.6.3)
Current plugin: Simple Location (version 4.1.10)
PHP version 7.3.12

Error Details
=============
An error of type E_ERROR was caused in line 197 of the file /var/www/wp-content/plugins/simple-location/includes/class-loc-metabox.php. Error message: Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone () in /var/www/wp-content/plugins/simple-location/includes/class-loc-metabox.php:197
Stack trace:
#0 /var/www/wp-content/plugins/simple-location/includes/class-loc-metabox.php(197): DateTimeZone->__construct('')
#1 /var/www/wp-content/plugins/simple-location/includes/class-loc-metabox.php(304): Loc_Metabox::save_meta('user', 5)
#2 /var/www/wp-includes/class-wp-hook.php(287): Loc_Metabox::save_user_meta(5)
#3 /var/www/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#4 /var/www/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#5 /var/www/wp-admin/user-edit.php(138): do_action('personal_option...', 5)
#6 /var/www/wp-admin/profile.php(18): require_once('/var/www/wp-adm...')
#7 {main}
  thrown

**Comment by dshanske** [comment]
This should be fixed the GitHub version. Working on a few other items before a release.
