### ISSUE TITLE
Update Profile Without Timezone Selected Causes Internal Server Error

### ISSUE THREAD

**Issue by jamesvandyne** [dshanske/simple-location#196]
When updating my profile on my blog failure to select a timezone  in the Last Report Location form results in a 500 error due to trying to access an index that doesn't exist. Selecting a timezone allows the page to save successfully.

My guess the reason for the failure is that because no value is selected, "timezone" isn't being posted to the server.

<img width="889" alt="image" src="https://user-images.githubusercontent.com/154726/96193632-83b8f080-0f83-11eb-967f-d15f112a40c6.png">

Error message: 

```
Notice: Undefined index: location_icon in /var/www/html/wp-content/plugins/simple-location/includes/class-loc-metabox.php on line 178

Fatal error: Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone () in /var/www/html/wp-content/plugins/simple-location/includes/class-loc-metabox.php:197 Stack trace: #0 /var/www/html/wp-content/plugins/simple-location/includes/class-loc-metabox.php(197): DateTimeZone->__construct('') #1 /var/www/html/wp-content/plugins/simple-location/includes/class-loc-metabox.php(304): Loc_Metabox::save_meta('user', 1) #2 /var/www/html/wp-includes/class-wp-hook.php(287): Loc_Metabox::save_user_meta(1) #3 /var/www/html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #4 /var/www/html/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #5 /var/www/html/wp-admin/user-edit.php(138): do_action('personal_option...', 1) #6 /var/www/html/wp-admin/profile.php(18): require_once('/var/www/html/w...') #7 {main} thrown in /var/www/html/wp-content/plugins/simple-location/includes/class-loc-metabox.php on line 197
```

**Comment by dshanske** [comment]
This has already been fixed...I was working on another problem before pushing... but I'll push then work on the other problem as unrelated.

**Comment by jamesvandyne** [comment]
I searched the issues but didn't see this issue anywhere, but am glad to hear it's already fixed in dev. Thank you @dshanske!
