### ISSUE TITLE
Feature Request: Custom Taxonomy with Dynamic Hierarchy

### ISSUE THREAD

**Issue by kartguru** [dshanske/simple-location#200]
Use geo_address to create categories in a logical hierarchy, i.e.  Country > Region > City.  This allows for filtering based on a custom taxonomy, an alternative way to display posts to the map based layouts.

Potentially optional levels if going as granular as #198 suggests (i.e. https://github.com/predicthq/address-formatter-php)

Thanks for considering and kudos on the simple yet effective plugin

**Comment by dshanske** [comment]
Related #40

**Comment by dshanske** [comment]
Properties would be http://microformats.org/wiki/h-adr

**Comment by dshanske** [comment]
Same names used by various services

**Comment by kartguru** [comment]
definitely a standard format

**Comment by dshanske** [comment]
Little different than requested....but done.

**Comment by kartguru** [comment]
your 'little different' makes a lot of sense @dshanske. The interpretation/implementation is slick, thats for sure. thanks for following up with my suggestion.

The issue I've come across so far is that the terms are not selected upon updating the post. I had to manually do so after setting 'show_in_rest' or 'show_in_quick_edit' to true. I think you have set as false as your plugin is doing all the hardwork (which makes sense), its just not selected at the moment.

apart from that its awesome. the Country, Region, Locality breakdown is really nice.

**Comment by dshanske** [comment]
It's to prevent selecting multiple terms as it should be only one per post. The JS should set it automatically. I'll look into why it might not be. I released a series of updates this week to refine the feature after deployment. I still want to add a few more, such as a front end landing page that shows all terms and a term merge capability.

**Comment by kartguru** [comment]
hey @dshanske, just some more feedback from testing this new feature. 

I had two examples of localities not becoming children of regions when region existed. 

It seemed to function as expected when a new region and locality were added to a pre-existing country.

will let you know if i see any other querky stuff. cheers

**Comment by dshanske** [comment]
I'm doing some additional unit testing now on this. I found a scenario already I fixed.
