### ISSUE TITLE
Fatal Error when activating plugin

### ISSUE THREAD

**Issue by dougbeal** [dshanske/simple-location#22]
Fatal error: Class 'WP_Geo_Meta' not found in wp-content/plugins/simple-location/simple-location.php on line 26

Does simple-location have plugins its dependent on?

I'm running WP 4.7.4.

**Comment by dshanske** [comment]
That is strange. I will look into it. Is this the WordPress.org version?

**Comment by dshanske** [comment]
I think I know what the problem is. Expect an update soon

**Comment by dougbeal** [comment]
It works!
