### ISSUE TITLE
Simple Location has issues with timestamps when using micropub clients like OwnYourGram and OwnYourCheckin

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/simple-location#23]
I've noticed the issue now with both OwnYourGram as well as OwnYourCheckin. When using these (and possibly other micropub services) the date and time displayed on the ultimate post has problems when using in conjunction with Simple Location. (And turning off Simple Location causes the error to go away.)

In general, the post is published with:
"Change Displayed Timezone" checked
geo_timezone is set properly as America/Los_Angeles (my timezone)
"Published on" time shows as UTC +00:00 in the admin UI

Yet the physical time that displays on the post is always: December 31, 1969
I have a feeling there's a small flaw in the calculation or set up somewhere causing the time not to display properly in the actual post. Otherwise it seems to be working as expected. 

eg: https://dougbeal.com/2017/05/02/30/ (using OwnYourGram)
eg: http://boffosocko.com/2017/05/09/checkin-dicks-sporting-goods/ (using OwnYourCheckin)

**Comment by dshanske** [comment]
This is an issue with Micropub I've sent a PR to fix. But I am pushing an update to Simple Location to assist in setting the timezone, which wasn't previously supported. The two will work together.
