### ISSUE TITLE
Fatal Error in class-wp-rest-controller.php on line 434

### ISSUE THREAD

**Issue by lamefe** [dshanske/simple-location#238]
Since 5.0 it now throws another fatal error when opening the post editor: 

Fatal error: Uncaught TypeError: call_user_func(): 
Argument #1 ($callback) must be a valid callback, class "__CLASS__" not found in /wp-includes/rest-api/endpoints/class-wp-rest-controller.php:434 Stack trace: 
#0 /wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(1969): WP_REST_Controller->add_additional_fields_to_object(Array, Object(WP_REST_Request)) 
#1 /wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(568): WP_REST_Posts_Controller->prepare_item_for_response(Object(WP_Post), Object(WP_REST_Request)) 
#2 /wp-includes/rest-api/class-wp-rest-server.php(1171): WP_REST_Posts_Controller->get_item(Object(WP_REST_Request)) 
#3 /wp-includes/rest-api/class-wp-rest-server.php(1018): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wp/v2/posts/(?...', Array, NULL) 
#4 /wp-includes/rest-api.php(535): WP_REST_Server->dispatch(Object(WP_REST_Request)) 
#5 /wp-includes/rest-api.php(2884): rest_do_request(Object(WP_REST_Request)) 
#6 [internal function]: rest_preload_api_request(Array, '/wp/v2/posts/69...') 
#7 /wp-includes/block-editor.php(633): array_reduce(Array, 'rest_preload_ap...', Array) 
#8 /edit-form-blocks.php(77): block_editor_rest_api_preload(Array, Object(WP_Block_Editor_Context)) 
#9 //post.php(187): require('/homepages/22/d...') 
#10 {main} thrown in /wp-includes/rest-api/endpoints/class-wp-rest-controller.php on line 434

**Comment by dshanske** [comment]
Unfortunately, it doesn't say where the error is coming from, it is something linking into the . I'm running it on a production site without an error. But I'll try to find it. Judging by the error, I may be linking something in early enough for the regular REST API, but too late for block. I use the Classic Editor, so wouldn't have noticed. Give me a bit and I'll figure it out.

**Comment by dshanske** [comment]
Took me some time, but I found the line generating this and fixed it. Version 5.0.1 will be out shortly.

**Comment by lamefe** [comment]
Great! Many thanks, works perfectly now.
