### ISSUE TITLE
Cannot modify header information

### ISSUE THREAD

**Issue by lamefe** [dshanske/simple-location#239]
Sorry, I don't get it run. I have it on two live installations and at one test. All three don't work properly. Doesn't matter wich geo provider, or even switched off 
live 6.1 TT2
live 6.1 T17
local 6.0.3 TT2 

I already tried to set up full new installation on all three. But I slowly think I'm doing something wrong. 

Undefined array key 0 in /wp-content/plugins/simple-location/includes/functions.php on line 510
Warning:  Undefined array key 0 in /wp-content/plugins/simple-location/includes/functions.phpon line 510
Warning:  Cannot modify header information - headers already sent by (output started at /wp-content/plugins/simple-location/includes/functions.php:510) in /wp-includes/rest-api/class-wp-rest-server.php</b> on line 1752
{"latitude":"49.4927749","longitude":"11.4715236","url":"http:\/\/www.happurg.de\/"}

or: 

Warning:  Undefined array key "display_name" in/wp-content/plugins/simple-location/includes/location/class-location-provider-address.php on line 57
Warning:  Cannot modify header information - headers already sent by (output started at /wp-content/plugins/simple-location/includes/location/class-location-provider-address.php:57) in /wp-includes/rest-api/class-wp-rest-server.php on line 1752
{"latitude":"48.6589138","longitude":"9.6707545","zoom":"14"}

or:

Fatal error:  Uncaught Error: Call to a member function set() on null in wp-content/plugins/simple-location/includes/class-rest-geo.php:497
Stack trace:
#0 //wp-includes/rest-api/class-wp-rest-server.php(1171): REST_Geo::geocode(Object(WP_REST_Request))
#1 /wp-includes/rest-api/class-wp-rest-server.php(1018): WP_REST_Server-&gt;respond_to_request(Object(WP_REST_Request), '/sloc_geo/1.0/g...', Array, NULL)
#2 /wp-includes/rest-api/class-wp-rest-server.php(442): WP_REST_Server-&gt;dispatch(Object(WP_REST_Request))
#3 /wp-includes/rest-api.php(410): WP_REST_Server-&gt;serve_request('/sloc_geo/1.0/g...')
#4 /wp-includes/class-wp-hook.php(308): rest_api_loaded(Object(WP))
#5 /wp-content/plugins/simple-location/includes/class-rest-geo.php</b> on line <b>497

**Comment by lamefe** [comment]
An error of type E_ERROR was caused in line 40 of the file /wp-content/plugins/simple-location/templates/loc-metabox.php. Error message: Uncaught Error: Call to a member function set() on null in /wp-content/plugins/simple-location/templates/loc-metabox.php:40
Stack trace:
#0 /wp-includes/template.php(783): require_once()
#1 /wp-content/plugins/simple-location/includes/class-geo-base.php(116): load_template('/homepages/22/d...')
#2 /wp-admin/includes/template.php(1409): Geo_Base::metabox(Object(WP_Post), Array)
#3 /wp-admin/includes/post.php(2249): do_meta_boxes(Object(WP_Screen), 'side', Object(WP_Post))
#4 /wp-admin/edit-form-blocks.php(316): the_block_editor_meta_boxes()
#5 /wp-admin/post.php(187): require('/homepages/22/d...')
#6 {main}
 thrown

**Comment by dshanske** [comment]
Added checks for undeclared variables here.
