### ISSUE TITLE
Error when saving post caused by class-astronomical-calculator.php

### ISSUE THREAD

**Issue by asuh** [dshanske/simple-location#241]
After making updates to a post, I am now getting the following error:

> When seeking help with this issue, you may be asked for some of the following information:
> WordPress version 6.1.1
> Active theme: Asuh (version 7.1)
> Current plugin: Simple Location (version 5.0.4)
> PHP version 8.1.9
> 
> 
> 
> Error Details
> =============
> An error of type E_ERROR was caused in line 125 of the file /wp/wp-content/plugins/simple-location/includes/class-astronomical-calculator.php. Error message: Uncaught TypeError: date_sunrise(): Argument #3 ($latitude) must be of type ?float, string given in /wp/wp-content/plugins/simple-location/includes/class-astronomical-calculator.php:125
> Stack trace:
> #0 /wp/wp-content/plugins/simple-location/includes/class-astronomical-calculator.php(125): date_sunrise(1670940683, 0, '', '', 90.583333)
> #1 /wp/wp-content/plugins/simple-location/includes/class-astronomical-calculator.php(240): Astronomical_Calculator->get_timestamp(1670940683, 'sunrise')
> #2 /wp/wp-content/plugins/simple-location/includes/data-functions.php(71): Astronomical_Calculator->is_daytime(1670940683)
> #3 /wp/wp-content/plugins/simple-location/includes/class-geo-base.php(1127): is_day_post(Object(WP_Post))
> #4 /wp/wp-includes/class-wp-hook.php(310): Geo_Base::save_post_meta(2085)
> #5 /wp/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(true, Array)
> #6 /wp/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
> #7 /wp/wp-includes/post.php(4717): do_action('save_post', 2085, Object(WP_Post), false)
> #8 /wp/wp-includes/revision.php(337): wp_insert_post(Array, true)
> #9 /wp/wp-includes/revision.php(191): _wp_put_post_revision(Array)
> #10 /wp/wp-includes/class-wp-hook.php(310): wp_save_post_revision(1927)
> #11 /wp/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
> #12 /wp/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
> #13 /wp/wp-includes/post.php(4686): do_action('post_updated', 1927, Object(WP_Post), Object(WP_Post))
> #14 /wp/wp-includes/post.php(4819): wp_insert_post(Array, false, true)
> #15 /wp/wp-admin/includes/post.php(426): wp_update_post(Array)
> #16 /wp/wp-admin/post.php(227): edit_post()
> #17 {main}
>   thrown

**Comment by dshanske** [comment]
Resolved in recent push by checking for null values.
