### ISSUE TITLE
Fatal Error on Activation

### ISSUE THREAD

**Issue by davidized** [dshanske/simple-location#27]
When attempting to activate version 3.1.0 the following fatal error is generated and activation fails:

> Notice: Undefined index: args in /srv/www/davidized/htdocs/wp-includes/functions.php on line 5098
> 
> Warning: require_once(/srv/www/davidized/htdocs/wp-content/plugins/simple-location/includes/class-geo-meta.php): failed to open stream: No such file or directory in /srv/www/davidized/htdocs/wp-content/plugins/simple-location/simple-location.php on line 26
> 
> Fatal error: require_once(): Failed opening required '/srv/www/davidized/htdocs/wp-content/plugins/simple-location/includes/class-geo-meta.php' (include_path='.:/usr/share/php') in /srv/www/davidized/htdocs/wp-content/plugins/simple-location/simple-location.php on line 26

It looks like there is no such file ```includes/class-geo-meta.php```

**Comment by dshanske** [comment]
Resolved.
