### ISSUE TITLE
Enabled plugin stops attachment metadata from being written to database

### ISSUE THREAD

**Issue by lostfocus** [dshanske/simple-location#286]
When the plugin is enabled, WordPress doesn't save `_wp_attachment_metadata` to the database after uploading a file. It doesn't make a difference which file type the file is or if it has location data or not. A file uploaded disabling the plugin will save the metadata.  

There is also a PHP warning (`PHP Warning:  Undefined array key "geo_latitude" in /var/www/wp/wp-content/plugins/simple-location/includes/class-sloc-media-metadata.php on line 226`) which might be related.

**Comment by dshanske** [comment]
Will look at this immediately. Probably an error check.

**Comment by dshanske** [comment]
Try it now. It wasn't returning if there was no location in the file. I fixed it I believe.

**Comment by lostfocus** [comment]
That's working now, thanks!
