### ISSUE TITLE
Last update turned off checkins in Post Kinds metabox

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/simple-location#34]
It may have been something else, though I haven't changed anything else substantively recently...

When I updated simple locations with the new release, I think it disabled the visibility for checkins with Post Kinds Plugin. IIRC, there was a check that one did to see if the other was installed and enabled them. Perhaps changes in Post Kinds and Simple Location haven't kept abreast with each other as I believe the on/off in the Post Kinds plugin also moved a version or two back as well.

I want to say that I'd been manually changing the code for a while to show checkins within the metabox, though perhaps after the refactoring of Post Kinds a few months back, perhaps I hadn't and so it was updating Simple Location that turned it off yesterday. I can't be 100% sure, and the number of people using the two in tandem is surely small, so I thought I'd mention it.

In the meanwhile, (as a reminder to myself) I've manually hard coded checkins back on.

**Comment by dshanske** [comment]
That was turned off in Post Kinds several versions ago as not complete. It can still be set by Micropub. Simple Location doesn't have this functionality.
