### ISSUE TITLE
People & Places and Simple Location

### ISSUE THREAD

**Issue by xavierroy** [dshanske/simple-location#39]
I use People & Places(https://github.com/beaulebens/people-places) in addition to Simple Location. Can anything be 'copied' from there? especially the UI/place listings?

**Comment by dshanske** [comment]
What do you mean by copied?

**Comment by xavierroy** [comment]
I should've been more clearer. The People & Places plugin uses a taxonomy structure to store a location information. Can Simple Location tie in to that or use a similar structure? That's what I meant.

**Comment by dshanske** [comment]
It is already in, but not implemented yet. Venues as a taxonomy is planned

**Comment by dshanske** [comment]
For now, the location taxonomy handles coarse location. Will be revisiting fine location in future.
