### ISSUE TITLE
Location textfield in New Post form should have flexible width

### ISSUE THREAD

**Issue by quimgil** [dshanske/simple-location#46]
The Location field in the New Post form seems to have a fixed width, and it will invade the right column in a narrow window (in my case, the result of a portrait monitor). 
![screenshot from 2017-12-19 10-15-12](https://user-images.githubusercontent.com/1899541/34149698-33c3d0fa-e4a6-11e7-9346-949735ea733e.png)

**Comment by dshanske** [comment]
I may take a crack at improving the design of the box overall, but next update will add flexible width

**Comment by dshanske** [comment]
Merged short term fix.

**Comment by quimgil** [comment]
Thank you very much!
