### ISSUE TITLE
Private Geofencing

### ISSUE THREAD

**Issue by dshanske** [dshanske/simple-location#49]
Hide coordinates if location is inside a zone. For example, around one's home.

**Comment by dshanske** [comment]
The public private option is based on the geodata guidelines for WordPress for compatibility sake. But I want to brainstorm new ways to intelligently set it automatically. May have to wait for venues.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/dshanske/simple-location/issues/49" class="u-in-reply-to"></a>Might also add another display option in addition to "Hide", "Show desc & map", and "Desc. only":

The ability to display the description of the location but without outputting the GPS coordinates into the page source (even if it doesn't display). This way people could store their GPS data in their back end and indicate they're somewhere (like Home) without giving away the specific location of their home (or other) address.

**Comment by dshanske** [comment]
That's what description only is supposed to be

**Comment by dshanske** [comment]
In order to accomplish this, I would need to add zones.

**Comment by dshanske** [comment]
Basically, I have to store places.
