### ISSUE TITLE
Hiding location isn't saving properly/working as expected.

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/simple-location#54]
Seems like you'd addressed this in an earlier incarnation, but the most recent version isn't respecting the setting to "Hide" the location metadata on the post. (versus "Show description and Map" and "Description Only")

Upon save draft or publish it defaults back to "Show description and Map."

**Comment by dshanske** [comment]
I really wish that Wordp hadn't defined things so narrowly

**Comment by dshanske** [comment]
I am working on redoing the UI for this and will be looking at the logic as well

**Comment by chrisaldrich** [comment]
<a href="https://github.com/dshanske/simple-location/issues/54#issuecomment-357795327" class="u-in-reply-to"></a>For privacy, it might also be worth adding a fourth setting for something like "Description without GPS coordinates" this way one could visually indicate something like being at/posting from their "Home" but without including the GPS coordinates that are still machine readable within the page source for the "Description Only". They could still keep all of the other location meta-data on their back end however.

**Comment by dshanske** [comment]
Description only isn't supposed to include the coordinates.

**Comment by dshanske** [comment]
Can you check this again?

**Comment by chrisaldrich** [comment]
<a href="https://github.com/dshanske/simple-location/issues/54#issuecomment-362879219" class="u-in-reply-to"></a>Using the most recent update:
For public, it shows the expected location name with a link, a map, and machine readable gps coords.
For protected, it shows just the location name and the page source shows the machine readable gps coords
For private, it's still not saving properly and defaults back to public when the post is published.

**Comment by dshanske** [comment]
This is very strange. But I'll go back to it in a few days and have a look again.

**Comment by dshanske** [comment]
I've made some changes and am closing. It can be reopened if the current version does not address.
