### ISSUE TITLE
Thermometer icon shows with no data set

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/simple-location#55]
When posting with a location name and GPS coordinates, but without triggering the weather portion and no data appearing in the temp or humidity fields the plugin is displaying a thermometer icon.

I would expect that with no data or triggering the weather options, there would be no output display for weather at all.

Example: http://boffosocko.com/2018/01/13/snack-at-the-movie-theater-large-diet-coke-chicken-sausage-with-baguette-large-popcorn-with-butter/#ArcLight+Cinemas

**Comment by dshanske** [comment]
@chrisaldrich Has this been resolved?

**Comment by chrisaldrich** [comment]
This seems to have been fixed and I haven't seen it pop back up. Thanks!
