### ISSUE TITLE
[Feature] Map with all markers in a cat

### ISSUE THREAD

**Issue by interludic** [dshanske/simple-location#58]
Thank you! Only took minutes to setup and do what it says and what i need. 

Please change the way _"You can filter any query or archive by adding ?geo={all|public|text} to it to show only public posts with location. Adding /geo/all to the homepage or archive pages should also work."_

**Instead/as well to show a list of posts, a map with all the markers (preferably from a category) that link to the original post would be so cool!**

**Comment by dshanske** [comment]
The map with markers is in. Links to original posts not yet.
