### ISSUE TITLE
Add a marker link

### ISSUE THREAD

**Issue by thejeshgn** [dshanske/simple-location#62]
The link from the blog to OSM as of now looks like 

http://www.openstreetmap.org/#map=14/15.1756/73.9459

Can we modify it to

http://www.openstreetmap.org/?mlat=15.1756&mlon=73.9459#map=14/15.1756/73.9459

So it adds a marker and we know the spot exactly.

I can send a pull request.

**Comment by dshanske** [comment]
I should be able to do this quickly enough.

**Comment by dshanske** [comment]
@thejeshgn Committed to the 'providers' branch. Going to work on a bunch of other related enhancements before merging to master and distributing to Wordpress.org. The static map shows a marker now as well.

**Comment by thejeshgn** [comment]
Looks great. I will test tonight.
