### ISSUE TITLE
Latest 3.3.3 Version Causes Uncaught Error: Class 'Geo_Provider_' And Breaks Sites

### ISSUE THREAD

**Issue by timnolte** [dshanske/simple-location#68]
My WordPress instance is part of a multisite install. Latest version 4.9.4.

PHP Fatal error:  Uncaught Error: Class 'Geo_Provider_' not found in /home/ndigita4/public_html/wp-content/plugins/simple-location/includes/class-loc-config.php:603
Stack trace:
#0 /home/ndigita4/public_html/wp-content/plugins/simple-location/includes/class-geo-data.php(402): Loc_Config::default_reverse_provider(Array)
#1 /home/ndigita4/public_html/wp-content/plugins/simple-location/includes/class-loc-view.php(23): WP_Geo_Data::get_geodata(Object(WP_Post))
#2 /home/ndigita4/public_html/wp-content/plugins/simple-location/includes/class-loc-view.php(121): Loc_View::get_location()
#3 /home/ndigita4/public_html/wp-includes/class-wp-hook.php(286): Loc_View::location_content('<p><img data-at...')
#4 /home/ndigita4/public_html/wp-includes/plugin.php(203): WP_Hook->apply_filters('<p><img data-at...', Array)
#5 /home/ndigita4/public_html/wp-includes/formatting.php(3313): apply_filters('the_content', '<img class="ali...')
#6 /home/ndigita4/public_html/wp-includes/class-wp-hook.php(288): wp_trim_excerpt('<img class="ali...')
#7 /home/ndi in /home/ndigita4/public_html/wp-content/plugins/simple-location/includes/class-loc-config.php on line 603

**Comment by timnolte** [comment]
FYI, disabling the plugin fixes the problem.

**Comment by dshanske** [comment]
It must be the default isn't being set. Can you save the configuration page and tell me if this fixes the problem? Either way, will issue a fix.

**Comment by dshanske** [comment]
I'm releaseing Version 3.3.4 to set the default if not set.

**Comment by timnolte** [comment]
Unfortunately my plugin auto-updates happened before I got a chance to try saving the settings page to see if that would fix it. My site is working after the update to 3.3.4.
