### ISSUE TITLE
Add Support for Location Weather

### ISSUE THREAD

**Issue by dshanske** [dshanske/simple-location#7]
Add support for noting current weather conditions at the location.

**Comment by dshanske** [comment]
Adding support for weather providers is the same as support for map providers. Abstract class with common outputs.

**Comment by dshanske** [comment]
Currently, want to optionally record temperature and a current conditions string as a minimum, maybe some extra properties for extensions later, like windspeed, feels like, etc.

**Comment by dshanske** [comment]
I need to decide on sitewide weather display, not just posts.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/dshanske/simple-location/issues/7" class="u-in-reply-to"></a>Perhaps build the basic functionality for posts and then add a sidebar widget and or code snippet one could throw into a header/footer to display elsewhere?

**Comment by miklb** [comment]
> decide on sitewide weather display

maybe a widget that you set a default zip code location?

**Comment by chrisaldrich** [comment]
<a href="https://github.com/dshanske/simple-location/issues/7" class="u-in-reply-to"></a>Some prior art for research: https://wordpress.org/plugins/tags/weather-widget/

**Comment by dshanske** [comment]
Default zip or coordinates?

**Comment by dshanske** [comment]
Also, could use #10 to set

**Comment by dshanske** [comment]
Initial version in development. Will be doing more tweaks and improvements before deployed to stable.
