### ISSUE TITLE
Affects the status of private posts

### ISSUE THREAD

**Issue by vishae** [dshanske/simple-location#70]
I've noticed this issue for a little while now but it's only today that I took the time to try and weed out the source.

Whenever I update a post marked as private (visibility set to private), the post would get published to public instead. Even when I edit the post to try to set it to private again, it still remains public. I have to go to the All Post (edit.php) page and quick edit the post to change the privacy there.

It's only when I deactivated simple-locations this issue stopped happening and I can update and change the privacy of my posts in the indvidual post editing page.

**Comment by chrisaldrich** [comment]
Replied to [Affects the status of private posts · Issue #70 · dshanske/simple-location](https://github.com/dshanske/simple-location/issues/70) by [![vishae](https://avatars3.githubusercontent.com/u/6110232?s=88&amp;v=4)vishae](https://github.com/vishae) _( GitHub)_

&gt; I've noticed this issue for a little while now but it's only today that I took the time to try and weed out the source. Whenever I update a post marked as private (visibility set to private), the post would get published to the public instead. Even when I edit the post to try to set it to private again, it still remains public. I have to go to the All Post (edit.php) page and quick edit the post to change the privacy there. It's only when I deactivated simple-locations this issue stopped happening and I can update and change the privacy of my posts in the indvidual post editing page.

I could have sworn I filed this as an issue before myself, but I’m not seeing it in the queue. Perhaps I mentioned in chat somewhere?

Simple location’s privacy setting seems to override the post’s public/private settings on my site as well. Perhaps it’s a naming conflict (function/filter/etc.) with [WP’s core content visibility code](https://codex.wordpress.org/Content_Visibility)?

In any case, I can’t make a post private while Simple Location is installed/activated either. This seems to happen regardless of other plugins. I do seem to be able to use @vishae’s method of using the quick edit option to change a post to private. I’m not sure if this may indicate a potential solution to the issue based on what is firing on a post save/update versus what fires on a quick edit save.

Additionally, I don’t seem to be able to mark a particular location as “private” in a post either as upon saving it it defaults back to public in the UI. I only seem to be able to use “public” or “protected” options for locations.

(Originally published at: https://boffosocko.com/2018/05/23/reply-to-vishaes-issue-affects-the-status-of-private-posts/)

**Comment by dshanske** [comment]
This is strange. Will investigate

**Comment by dshanske** [comment]
I am investigating this, but it is impossible. Post visibility is stored in the post itself, but visibility of location is in post meta. There shouldn't be any connection

**Comment by dshanske** [comment]
@vishae @chrisaldrich Can you retest this?

**Comment by vishae** [comment]
Updated to Simple Location 3.4.0 and I'm afraid I still can't publish privately.

**Comment by dshanske** [comment]
You are saying posts are still public or location is still public?

**Comment by vishae** [comment]
My posts are still posting as public

**Comment by dshanske** [comment]
Publish the post privately or the location? I keep trying to solve the privacy issue

**Comment by vishae** [comment]
I'm trying to publish the post privately, as in setting the WP post to private. But it doesn't work, no matter whether this is a new post or changing an existing post to private.

**Comment by dshanske** [comment]
@vishae 3.5.1 is out. Care to try again?
