### ISSUE TITLE
Issues · dshanske/simple-location

### ISSUE THREAD

**Issue by dougbeal** [dshanske/simple-location#74]
` PHP Notice: Undefined index: latitude in /var/www/html/wp-content/plugins/simple-location/includes/class-geo-data.php on line 119
PHP Notice: Undefined index: latitude in /var/www/html/wp-content/plugins/simple-location/includes/class-geo-data.php on line 120
PHP Notice: Undefined index: longitude in /var/www/html/wp-content/plugins/simple-location/includes/class-geo-data.php on line 119
PHP Notice: Undefined index: longitude in /var/www/html/wp-content/plugins/simple-location/includes/class-geo-data.php on line 121`

[](https://github.com/dshanske/simple-location/issues)

(Originally published at: https://crw.moe/b/ZW)

**Comment by dshanske** [comment]
I believe this is resolved in the latest dev version. Reopen if not.

**Comment by asuh** [comment]
I'm getting a similar message if latitude is missing:
`Undefined index: latitude in /[..]/plugins/simple-location/includes/class-geo-data.php on line 237`

Adding `isset` to `$geo['latitude']`, wrapped around the conditional, fixed the issue for me.
