### ISSUE TITLE
Look into Air Quality/Fire Conditions

### ISSUE THREAD

**Issue by dshanske** [dshanske/simple-location#87]

**Comment by thejeshgn** [comment]
Are you planning to add current status or status at the time of publishing?

**Comment by dshanske** [comment]
The current weather code, which I was looking to add to, retrieves current conditions at the time of retrieval only. There is a widget for real time and one that saves conditions into a post, attachment, comment, etc.

**Comment by dshanske** [comment]
This is technically supported now, though provider support is limited
