### ISSUE TITLE
Adding Wikimedia maps

### ISSUE THREAD

**Issue by thejeshgn** [dshanske/simple-location#88]
May be something to track. 
https://foundation.wikimedia.org/wiki/Maps_Terms_of_Use

It can be a great addition as there are multi language support. Say Kannada (https://maps.wikimedia.org/?lang=kn#16/12.9862/77.5895) which no other FOSS providers do.

**Comment by dshanske** [comment]
@thejeshgn I'm happy to add it, but I can't find an instruction page on how to use their tools outside of mediawiki. If I can find some instructions, I'm happy to add it.

**Comment by dshanske** [comment]
Finally found it... https://m.mediawiki.org/wiki/Wikimedia_Maps/2015-2017/Technical_Implementation

**Comment by dshanske** [comment]
Set up a quick support option, no caching yet.

**Comment by thejeshgn** [comment]
@dshanske thank you. I missed your previous comments. Sorry about that.
