### ISSUE TITLE
Possible issue with memory?

### ISSUE THREAD

**Issue by ghost** [dshanske/simple-location#90]
Two entries from my error log. Not sure if something else is the cause and simple-location merely failed to allocate memory due to a previous chain of events, but throwing it her in case anybody else is experiencing.

[Mon Nov 19 09:48:14.758699 2018] [:error] [pid 17414] [client 220.243.136.45:58949] PHP Fatal error: Out of memory (allocated 18874368) (tried to allocate 737280 bytes) in /var/www/html/wp-content/plugins/simple-location/includes/class-loc-timezone.php on line 35 

[Mon Nov 19 09:48:14.758903 2018] [:error] [pid 17475] [client 220.243.136.124:16819] PHP Fatal error: Out of memory (allocated 18874368) (tried to allocate 737280 bytes) in /var/www/html/wp-content/plugins/simple-location/includes/class-loc-timezone.php on line 35

**Comment by dshanske** [comment]
Well, I have a few optimization options I can try regardless

**Comment by dshanske** [comment]
This is a really big array that maps location to timezone. There are also services that do this, but I like doing things locally.

**Comment by dshanske** [comment]
I think I redesigned this to try and reduce the load. Reopen if needed.
