### ISSUE TITLE
2.5.1 outputs a block of markup

### ISSUE THREAD

**Issue by asuh** [dshanske/simple-location#95]
Updated and tested out latest version. I'm including a screenshot of what I see. It appears to be a block of text that isn't turning into HTML for some reason. 

I've since deleted the post but this could just be my theme, I'm not sure.

Screenshot:
![screen shot 2018-12-20 at 00 46 01](https://user-images.githubusercontent.com/454064/50273988-f3460f00-03f0-11e9-8a35-afe237c7fae8.png)

**Comment by dshanske** [comment]
I don't see that I am escaping content anywhere. How can I help you troubleshoot?

**Comment by dshanske** [comment]
Is this still an issue?

**Comment by asuh** [comment]
Not anymore, was an issue with my theme.
