### ISSUE TITLE
Simple Location's Last Seen widget is revealing private locations

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/simple-location#98]
Using the version 3.5.2 of Simple Location, I'm most recently checked into a location that is marked as private, but the location widget indicates "Private" followed by the exact street address to the private location to which I'm checked in. Previously the widget showed the most recent public location, but now it's explicitly uncovering private locations.

Perhaps it's related to the recent fix that was causing private posts to be marked public? https://github.com/dshanske/simple-location/issues/70

![simple location private last seen](https://user-images.githubusercontent.com/5882943/50378745-d4609c00-05ed-11e9-8760-cc26b846fd56.PNG)

(Originally published at https://boffosocko.com/2018/12/22/simple-locations-last-seen-widget-is-revealing-private-locations/)

**Comment by dshanske** [comment]
@chrisaldrich Log out and look again?

**Comment by dshanske** [comment]
I'm replacing the word Private with Hidden
